version: '3'

services:
  # フロントエンド
  nuxt:
    container_name: pripla_nuxt
    hostname: pripla_nuxt
    image: node:15.2.0-alpine3.10
    ports:
      - ${APP_EXPOSE_PORT}:${APP_PORT}
    working_dir: /var/www
    command: yarn start
    volumes:
      - ./:/var/www
    environment:
      HOST: ${APP_HOST}
    networks:
      - pripla
    restart: always

networks:
  pripla:
    external: true
